name: Build Docker Image

on: push
  #on: workflow_dispatch

jobs:

  
  #expressions:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Get Expressions
  #      run:  github.com

  build-to-DHub:
    runs-on: ubuntu-latest
    steps:

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t reactappimg:v1 .
          docker tag reactappimg:v1 frankisinfotech/cohort-app:v1
          docker push frankisinfotech/cohort-app:v1


  build-to-AWSECR:
    runs-on: ubuntu-latest
    steps:

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}


